import { Inter } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/SmoothScroll";
import Scene from "./components/Scene";
import Navbar from "./components/Navbar";

const mainFont = Inter({ subsets: ["latin"], weight: ["400", "700", "900"] });

export const metadata = {
  title: "Nour Gamil Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${mainFont.className} bg-black text-white`}>
        <SmoothScroll>
          <Navbar />
          <div className="fixed inset-0 -z-10">
            <Scene />
          </div>
          <main className="relative z-10">{children}</main>
        </SmoothScroll>
      </body>
    </html>
  );
}
