import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/SmoothScroll";
import Scene from "./components/Scene";
import Navbar from "./components/Navbar";

import { Inter, Montserrat } from 'next/font/google';

const mainFont = Inter({ subsets: ['latin'], weight: ['400', '700', '900'] });
const displayFont = Montserrat({ subsets: ['latin'], weight: ['900'] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${mainFont.className} bg-black text-white`}>
        <SmoothScroll>
          <Navbar /> 
          <div className="fixed inset-0 -z-10">
            <Scene/>
          </div>
          <main className="relative z-10">{children}</main>
        </SmoothScroll>
      </body>
    </html>
  );
}
